apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app
  namespace: demo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      serviceAccountName: demo-app
      containers:
        - name: demo-app
          # Replace with your signed ECR image after pipeline runs
          image: 061083040518.dkr.ecr.us-east-1.amazonaws.com/devops-demo-app@sha256:6032212c5e2704fd017ac09ba2251e929da682bad5bca0260b5591eb67a2dc19
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
